name: Build and upload to PyPI

# Only run this action when a new release is 
on: [release]

jobs:

  build_package:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Needed for `setuptools-scm`
          fetch-depth: 0

      - name: Build sdist
        run: pipx run build --sdist

      - name: Build wheel
        run: pipx run build --wheel

      - uses: actions/upload-artifact@v4
        with:
          path: dist

      - name: Debug
        run: echo "github.event_name = ${{ github.event_name }}; github.event.action = ${{ github.event.action }}"

  upload_package:
    name: Upload package to PyPI
    runs-on: ubuntu-latest
    needs: build_package
    environment:
      name: pypi
      url: https://pypi.org/p/losoto
      # For testing, use TestPyPI
      # url: https://test.pypi.org/p/losoto
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    # Upload to PyPI when release is released
    # Ref: https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=released#release
    if: github.event_name == 'release' && github.event.action == 'released'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist  # put artifacts where next action expects them to be
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1.13
        with:
          # For testing, use TestPyPI
          # repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
