name: Python package

on: 
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install
        run: pip install .[test]
      - name: Test
        run: tox
        continue-on-error: true
      # - name: Get Test Coverage
      #   uses: orgoro/coverage@v3.2
      #   with:
      #     coverageFile: coverage.xml
      #     token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Code Coverage Summary Report
      #   uses: irongut/CodeCoverageSummary@v1.3.0
      #   with:
      #     filename: coverage.xml
      #     badge: true
      #     format: markdown
      #     output: both
      - name: Get Test Coverage
        uses: insightsengineering/coverage-action@v2
        # with:
        #   path: ./cobertura.xml

      # - name: Run tests
      #   run: |
      #     pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=losoto tests/ | tee pytest-coverage.txt
      # - name: Report test coverage
      #   uses: MishaKav/pytest-coverage-comment@main
      #   with:
      #     pytest-coverage-path: ./pytest-coverage.txt
      #     junitxml-path: ./pytest.xml
