name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Install
        run: python -m pip install .
      - name: Test
        # Clumsy workaround to cast pytest exit status 5 (No tests were collected) to 0
        run: sh -c 'pytest tools/losoto_test.py; ret=$?; [ $ret = 5 ] && exit 0 || exit $ret'
