name: Python package

on: 
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install
        run: pip install .[test]
      - name: Test
        run: tox
        continue-on-error: true
      # - name: Get Test Coverage
      #   uses: orgoro/coverage@v3.2
      #   with:
      #     coverageFile: coverage.xml
      #     token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Test Coverage
        uses: insightsengineering/coverage-action@v2
        with:
          path: coverage.xml
          publish: true
          diff: true
          diff-branch: master
          togglable-report: true
